### PR TITLE
[FEATURE] Upgrade to lnd 0.7

### PR DESCRIPTION
**Pull request by gamer90**

### CODE REVIEW

**Comment by gamer90** [comment]
Retest this please.

**Comment by gamer90** [comment]
retest this please

**Comment by gamer90** [comment]
retest this please

**Comment by gamer90** [comment]
retest this please

**Comment by gamer90** [comment]
retest this please

**Comment by gamer90** [comment]
Retest this please.

**Comment by gamer90** [comment]
retest this please

**Comment by boodyvo** [comment]
Moved to https://github.com/LightningPeach/peach-wallet-desktop/pull/82.

**Pull request closed without merging**
